// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // CẢNH BÁO BẢO MẬT: Đã thay thế API Key thực tế bằng placeholder.
  // Đảm bảo không commit file này lên Git.
  static const String _apiKeyPlaceholder = 'YOUR_API_KEY_HERE';

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: _apiKeyPlaceholder,
    appId: '1:1096305927941:web:b3e225646bbfdc829ff96c',
    messagingSenderId: '1096305927941',
    projectId: 'movieapp-f4c5f',
    authDomain: 'movieapp-f4c5f.firebaseapp.com',
    databaseURL: 'https://movieapp-f4c5f-default-rtdb.firebaseio.com',
    storageBucket: 'movieapp-f4c5f.firebasestorage.app',
    measurementId: 'G-RH48TRXX3B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: _apiKeyPlaceholder,
    appId: '1:1096305927941:android:42888470aa991bfc9ff96c',
    messagingSenderId: '1096305927941',
    projectId: 'movieapp-f4c5f',
    databaseURL: 'https://movieapp-f4c5f-default-rtdb.firebaseio.com',
    storageBucket: 'movieapp-f4c5f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: _apiKeyPlaceholder,
    appId: '1:1096305927941:ios:364d585b5e4589629ff96c',
    messagingSenderId: '1096305927941',
    projectId: 'movieapp-f4c5f',
    databaseURL: 'https://movieapp-f4c5f-default-rtdb.firebaseio.com',
    storageBucket: 'movieapp-f4c5f.firebasestorage.app',
    iosBundleId: 'com.example.doanmobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: _apiKeyPlaceholder,
    appId: '1:1096305927941:ios:364d585b5e4589629ff96c',
    messagingSenderId: '1096305927941',
    projectId: 'movieapp-f4c5f',
    databaseURL: 'https://movieapp-f4c5f-default-rtdb.firebaseio.com',
    storageBucket: 'movieapp-f4c5f.firebasestorage.app',
    iosBundleId: 'com.example.doanmobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: _apiKeyPlaceholder,
    appId: '1:1096305927941:web:65694bc5fcd8a1ad9ff96c',
    messagingSenderId: '1096305927941',
    projectId: 'movieapp-f4c5f',
    authDomain: 'movieapp-f4c5f.firebaseapp.com',
    databaseURL: 'https://movieapp-f4c5f-default-rtdb.firebaseio.com',
    storageBucket: 'movieapp-f4c5f.firebasestorage.app',
    measurementId: 'G-RC5ZZZFY6W',
  );
}
